/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.praticas.visao;

import br.com.praticas.modelobeans.BeansPacientes;
import br.com.praticas.modelobeans.ModeloTabela;
import br.com.praticas.modeloconection.ConexaoBD;
import br.com.praticas.modelodao.DaoPaciente;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author HugoNathan
 */
public class FormPaciente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansPacientes pac = new BeansPacientes();
    DaoPaciente dao = new DaoPaciente();
    int flag=0;
    int resposta=0;
    
    public FormPaciente() {
        initComponents();
        preencherBairros();
        preencherCidades();
        preencherUf();
        
        preencherTabela("select paci_codigo,paci_nome,paci_telefone,paci_cpf,cidnome from pacientes inner join cidade on paci_cidcodigo = cidcodigo order by paci_nome;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jComboBoxBairro = new javax.swing.JComboBox();
        jComboBoxCidade = new javax.swing.JComboBox();
        jComboBoxUf = new javax.swing.JComboBox();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodPac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORMULÁRIO DE PACIENTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 0, 285, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("CEP:");

        jLabel21.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RN", "PB", "CE", "PE", "SP", "RJ", "SC" }));

        jLabel22.setText("Cidade:");

        jLabel25.setText("Nome:");

        jLabel26.setText("Data de Nascimento:");

        jLabel27.setText("RG:");

        jLabel28.setText("Telefone:");

        jLabel29.setText("CPF:");

        jTextFieldNome.setEnabled(false);

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Rua:");

        jLabel4.setText("Número:");

        jLabel5.setText("CEP:");

        jLabel6.setText("Complemento:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Cidade:");

        jLabel9.setText("UF:");

        jTextFieldRua.setEnabled(false);

        jTextFieldNumero.setEnabled(false);

        jTextFieldComplemento.setEnabled(false);

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.setEnabled(false);

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCidade.setEnabled(false);

        jComboBoxUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUf.setEnabled(false);

        jTextFieldCEP.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Endereço:");

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jLabel10.setText("Pesquisa:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNasc.setEnabled(false);

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setEnabled(false);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);

        jLabel11.setText("Cod:");

        jTextFieldCodPac.setEnabled(false);
        jTextFieldCodPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(482, 482, 482)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 910, 470);

        setSize(new java.awt.Dimension(950, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        if (jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o nome para continuar!" );
            jTextFieldNome.requestFocus();
        }else if(jFormattedTextFieldNasc.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Preencha a Data de Nascimento para continuar!" );
            jFormattedTextFieldNasc.requestFocus();
        }else if(jFormattedTextFieldCpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "Preencha o CPF para continuar!" );
            jFormattedTextFieldCpf.requestFocus();
        }else if(jFormattedTextFieldRg.getText().equals("   .   .   ")){
            JOptionPane.showMessageDialog(null, "Preencha o RG para continuar!" );
            jFormattedTextFieldRg.requestFocus();
        }else if(jFormattedTextFieldTelefone.getText().equals("   -     -    ")){
            JOptionPane.showMessageDialog(null, "Preencha o Telefone para continuar!" );
            jFormattedTextFieldTelefone.requestFocus();
        }else if(jTextFieldRua.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o nome da Rua para continuar!" );
            jTextFieldRua.requestFocus();
        }else if(jTextFieldNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Numero para continuar!" );
            jTextFieldNumero.requestFocus();
        }else if(jTextFieldCEP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o CEP para continuar!" );
            jTextFieldCEP.requestFocus();
        }else if(jTextFieldComplemento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o complemento para continuar!" );
            jTextFieldComplemento.requestFocus();
        

        }else
        if (flag == 1){

        
        pac.setNomePac(jTextFieldNome.getText());
        pac.setNasc(jFormattedTextFieldNasc.getText());
        pac.setCpf(jFormattedTextFieldCpf.getText());
        pac.setRg(jFormattedTextFieldRg.getText());
        pac.setTelefone(jFormattedTextFieldTelefone.getText());
        pac.setRua(jTextFieldRua.getText());
        pac.setNumero(jTextFieldNumero.getText());
        pac.setCep(jTextFieldCEP.getText());
        pac.setComplemento(jTextFieldComplemento.getText());
        pac.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
        pac.setNomeCidade((String) jComboBoxCidade.getSelectedItem());
        pac.setUF((String) jComboBoxUf.getSelectedItem());
        dao.Salvar(pac);
        preencherTabela("select paci_codigo,paci_nome,paci_telefone,paci_cpf,cidnome from pacientes inner join cidade on paci_cidcodigo = cidcodigo order by paci_nome;");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldComplemento.setEnabled(false);
        jComboBoxUf.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldCodPac.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCEP.setText("");
        jTextFieldComplemento.setText("");
        
        }
        else{
        pac.setNomePac(jTextFieldNome.getText());
        pac.setNasc(jFormattedTextFieldNasc.getText());
        pac.setCpf(jFormattedTextFieldCpf.getText());
        pac.setRg(jFormattedTextFieldRg.getText());
        pac.setTelefone(jFormattedTextFieldTelefone.getText());
        pac.setRua(jTextFieldRua.getText());
        pac.setNumero(jTextFieldNumero.getText());
        pac.setCep(jTextFieldCEP.getText());
        pac.setComplemento(jTextFieldComplemento.getText());
        pac.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
        pac.setNomeCidade((String) jComboBoxCidade.getSelectedItem());
        pac.setUF((String) jComboBoxUf.getSelectedItem());
        pac.setCodPac(Integer.parseInt( jTextFieldCodPac.getText()));
        dao.Alterar(pac);
        preencherTabela("select paci_codigo,paci_nome,paci_telefone,paci_cpf,cidnome from pacientes inner join cidade on paci_cidcodigo = cidcodigo order by paci_nome;");
        
         jTextFieldNome.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldComplemento.setEnabled(false);
        jComboBoxUf.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldCodPac.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCEP.setText("");
        jTextFieldComplemento.setText("");
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
         flag=1;
        jButtonNovo.setEnabled(true);
        
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jComboBoxUf.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag=2;
        
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jComboBoxUf.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
         
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldCpf.setEnabled(!true);
        jFormattedTextFieldRg.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jTextFieldNumero.setEnabled(!true);
        jTextFieldCEP.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jComboBoxUf.setEnabled(!true);
        jComboBoxCidade.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
        pac.setPesquisa(jTextFieldPesquisa.getText());
        BeansPacientes pac1 =  dao.buscaPaciente(pac);
        jTextFieldNome.setText(pac1.getNomePac());
        jTextFieldCodPac.setText(String.valueOf(pac1.getCodPac()));
        jFormattedTextFieldNasc.setText(pac1.getNasc());
        jFormattedTextFieldCpf.setText(pac1.getCpf());
        jFormattedTextFieldRg.setText(pac1.getRg());
        jFormattedTextFieldTelefone.setText(pac1.getTelefone());
        jTextFieldRua.setText(pac1.getRua());
        jTextFieldNumero.setText(pac1.getNumero());
        jTextFieldCEP.setText(pac1.getCep());
        jTextFieldComplemento.setText(pac1.getComplemento());
        jComboBoxBairro.setSelectedItem(pac1.getNomeBairro());
        jComboBoxCidade.setSelectedItem(pac1.getNomeCidade());
        jComboBoxUf.setSelectedItem(pac1.getUF());
        
        
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldCodPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodPacActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION){
        pac.setCodPac(Integer.parseInt(jTextFieldCodPac.getText()));
        dao.excluir(pac);
        preencherTabela("select paci_codigo,paci_nome,paci_telefone,paci_cpf,cidnome from pacientes inner join cidade on paci_cidcodigo = cidcodigo order by paci_nome;");
        
        jTextFieldCodPac.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCEP.setText("");
        jTextFieldComplemento.setText("");
        
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jComboBoxUf.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
         
        
        }
        
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        
        String nome_paciente =""+jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 1);
        conex.conexao();
        conex.executarSql("select *from pacientes where paci_nome='"+nome_paciente+"'");
                
        try {
            conex.rs.first();
            
            jTextFieldCodPac.setText(String.valueOf(conex.rs.getInt("paci_codigo")));
            jTextFieldNome.setText(conex.rs.getString("paci_nome"));
            jFormattedTextFieldNasc.setText(conex.rs.getString("paci_nasc"));
            jFormattedTextFieldCpf.setText(conex.rs.getString("paci_cpf"));
            jFormattedTextFieldRg.setText(conex.rs.getString("paci_rg"));
            jFormattedTextFieldTelefone.setText(conex.rs.getString("paci_telefone"));
            jTextFieldRua.setText(conex.rs.getString("paci_rua"));
            jTextFieldNumero.setText(conex.rs.getString("paci_numero"));
            jTextFieldCEP.setText(conex.rs.getString("paci_cep"));
            jTextFieldComplemento.setText(conex.rs.getString("paci_complemento"));
            
            
            ConexaoBD conexPesquisa = new ConexaoBD();
            conexPesquisa.conexao();
            conexPesquisa.executarSql("select *from bairro where baicodigo="+conex.rs.getInt("paci_baicodigo"));
            conexPesquisa.rs.first();
            jComboBoxBairro.setSelectedItem(conexPesquisa.rs.getString("bainome"));            
            conexPesquisa.desconecta();
            
            ConexaoBD conexPesquisa2 = new ConexaoBD();
            conexPesquisa2.conexao();
            conexPesquisa2.executarSql("select *from cidade where cidcodigo="+conex.rs.getInt("paci_cidcodigo"));
            conexPesquisa2.rs.first();
            jComboBoxCidade.setSelectedItem(conexPesquisa2.rs.getString("cidnome"));          
            conexPesquisa2.desconecta();
            
            ConexaoBD conexPesquisa3 = new ConexaoBD();
            conexPesquisa3.conexao();
            conexPesquisa3.executarSql("select *from uf where ufcodigo="+conex.rs.getInt("paci_ufcodigo"));
            conexPesquisa3.rs.first();
            jComboBoxUf.setSelectedItem(conexPesquisa3.rs.getString("ufnome")); 
                        
            conexPesquisa3.desconecta();
            
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldCpf.setEnabled(!true);
        jFormattedTextFieldRg.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jTextFieldNumero.setEnabled(!true);
        jTextFieldCEP.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jComboBoxUf.setEnabled(!true);
        jComboBoxCidade.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);


        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar Dados!");
        }
        conex.desconecta();
        
        
        
        
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        jTextFieldCodPac.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCEP.setText("");
        jTextFieldComplemento.setText("");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldComplemento.setEnabled(false);
        jComboBoxUf.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTablePacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePacientesMouseEntered

    public void preencherBairros(){
    
        conex.conexao();
        conex.executarSql("select *from bairro order by bainome");
        try {
            conex.rs.first();
            jComboBoxBairro.removeAllItems();
            do{
                jComboBoxBairro.addItem(conex.rs.getString("bainome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher os Bairros!"+ex);
        }
        
        conex.desconecta();
        
    }
    
      public void preencherCidades(){
    
        conex.conexao();
        conex.executarSql("select *from cidade order by cidnome");
        try {
            conex.rs.first();
            jComboBoxCidade.removeAllItems();
            do{
                jComboBoxCidade.addItem(conex.rs.getString("cidnome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher as Cidades!"+ex);
        }
        
        conex.desconecta();
        
    }
      
       public void preencherUf(){
    
        conex.conexao();
        conex.executarSql("select *from uf order by ufnome");
        try {
            conex.rs.first();
            jComboBoxUf.removeAllItems();
            do{
                jComboBoxUf.addItem(conex.rs.getString("ufnome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher os Estados"+ex);
        }
        
        conex.desconecta();
        
    }
       
       public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID","Nome","Contato","CPF","Cidade"};
        conex.conexao();
        conex.executarSql(Sql);
        
        try{
        conex.rs.first();
        do{
            dados.add(new Object[]{conex.rs.getInt("paci_codigo"),conex.rs.getString("paci_nome"),conex.rs.getString("paci_telefone"),conex.rs.getString("paci_cpf"),conex.rs.getString("cidnome")});
        }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Busque por outro médico!");
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTablePacientes.setModel(modelo);
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePacientes.getColumnModel().getColumn(0).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(400);
        jTablePacientes.getColumnModel().getColumn(1).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(2).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(3).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(4).setResizable(false);
        jTablePacientes.getTableHeader().setReorderingAllowed(false);
        jTablePacientes.setAutoResizeMode(jTablePacientes.AUTO_RESIZE_OFF);
        jTablePacientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxBairro;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxUf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodPac;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
