/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.praticas.visao;



import br.com.praticas.modeloconection.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HugoNathan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    FormMedico tela = new FormMedico();
    FormUsuario telaUsu = new FormUsuario();
    FormFuncionario telaFunc = new FormFuncionario();
    FormPaciente telaPac = new FormPaciente();
    FormAgenda telaAgenda = new FormAgenda();
    FormAgendamentos telaAgendamentos = new FormAgendamentos();
    
    TelaLogin telaLogin = new TelaLogin();
    
    
    
    
    public TelaPrincipal(String usuario) {
        initComponents();
        conecta.conexao();
        jLabelUsuario.setText(usuario);
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonMedicos = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadMedicos = new javax.swing.JMenuItem();
        jMenuItemCadPacientes = new javax.swing.JMenuItem();
        jMenuItemCadFuncionarios = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/people-doctor-male-icon.png"))); // NOI18N
        jButtonMedicos.setText("Médicos");
        jButtonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonMedicos);
        jButtonMedicos.setBounds(20, 40, 200, 100);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/sair.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonSair);
        jButtonSair.setBounds(560, 190, 110, 70);

        jButtonFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/cropped.png"))); // NOI18N
        jButtonFuncionarios.setText("Funcionários");
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonFuncionarios);
        jButtonFuncionarios.setBounds(240, 40, 200, 100);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/People-Patient-Male-icon.png"))); // NOI18N
        jButtonPaciente.setText("Pacientes");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonPaciente);
        jButtonPaciente.setBounds(460, 40, 200, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("CADASTROS");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(20, 10, 160, 30);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/agenda.png"))); // NOI18N
        jButtonAgenda.setText("Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(20, 180, 200, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("AGENDAMENTOS");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(20, 130, 240, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/emergency_icon.png"))); // NOI18N
        jButton1.setText("Verificar Agendamentos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButton1);
        jButton1.setBounds(240, 180, 230, 90);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/123_wallpaper_blue.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 700, 280);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("CADASTROS");
        jPanelInternal.add(jLabel6);
        jLabel6.setBounds(20, 10, 160, 30);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 20, 690, 280);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 20);

        jLabel4.setText("jLabel4");
        jInternalFrameBemVindo.getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 130, 34, 14);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(40, 20, 710, 330);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/logo_clinica.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 120, 294, 256);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(20, 360, 70, 20);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/praticas/imagens/123_wallpaper_blue.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 790, 390);

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadMedicos.setText("Médicos");
        jMenuItemCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadMedicos);

        jMenuItemCadPacientes.setText("Pacientes");
        jMenuItemCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadPacientes);

        jMenuItemCadFuncionarios.setText("Funcionários");
        jMenuItemCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadFuncionarios);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(793, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicosActionPerformed
        
        try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(tela == null){
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
        
    }//GEN-LAST:event_jMenuItemCadMedicosActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
    try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaUsu == null){
                    telaUsu = new FormUsuario();
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                }else{
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                }
                //FormUsuario tela = new FormUsuario();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }    
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
        conecta.desconecta();
        //System.exit(0);
        telaLogin.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
    TelaPrincipal tela = new TelaPrincipal("");
    tela.setVisible(true);
    dispose();

    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionariosActionPerformed
try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaFunc == null){
                    telaFunc = new FormFuncionario();
                    telaFunc.setVisible(true);
                    telaFunc.setResizable(false);
                }else{
                    telaFunc.setVisible(true);
                    telaFunc.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
        
        
//FormFuncionario tela = new FormFuncionario();
//tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncionariosActionPerformed

    private void jMenuItemCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacientesActionPerformed
        try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador") || conecta.rs.getString("usu_tipo").equals("Atendente") ){
                if(telaPac == null){
                    telaPac = new FormPaciente();
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }else{
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }

//FormPaciente tela = new FormPaciente();
//tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPacientesActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
    //System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicosActionPerformed
        
        try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(tela == null){
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
    }//GEN-LAST:event_jButtonMedicosActionPerformed

    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        
        try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaFunc == null){
                    telaFunc = new FormFuncionario();
                    telaFunc.setVisible(true);
                    telaFunc.setResizable(false);
                }else{
                    telaFunc.setVisible(true);
                    telaFunc.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
       try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador") || conecta.rs.getString("usu_tipo").equals("Atendente")|| conecta.rs.getString("usu_tipo").equals("Enfermeiro") ){
                if(telaPac == null){
                    telaPac = new FormPaciente();
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }else{
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed

        try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador") || conecta.rs.getString("usu_tipo").equals("Médico") || conecta.rs.getString("usu_tipo").equals("Atendente") || conecta.rs.getString("usu_tipo").equals("Enfermeiro")){
                if(telaAgenda == null){
                    telaAgenda = new FormAgenda();
                    telaAgenda.setVisible(true);
                    telaAgenda.setResizable(false);
                }else{
                    telaAgenda.setVisible(true);
                    telaAgenda.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
        
        
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         try {
            conecta.executarSql("select * from usuarios where usu_nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador") || conecta.rs.getString("usu_tipo").equals("Médico") || conecta.rs.getString("usu_tipo").equals("Atendente") || conecta.rs.getString("usu_tipo").equals("Enfermeiro")){
                if(telaAgendamentos == null){
                    telaAgendamentos = new FormAgendamentos();
                    telaAgendamentos.setVisible(true);
                    telaAgendamentos.setResizable(false);
                }else{
                    telaAgendamentos.setVisible(true);
                    telaAgendamentos.setResizable(false);
                }
       
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem permissões para esta funcionalidade!\n Contate o Administrador do Sistema."+ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonMedicos;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadFuncionarios;
    private javax.swing.JMenuItem jMenuItemCadMedicos;
    private javax.swing.JMenuItem jMenuItemCadPacientes;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
